-- MAGNITUDE ANALYSIS

SELECT TOP 3 * FROM gold.dim_customers;
SELECT TOP 3 * FROM gold.dim_products;
SELECT TOP 3 * FROM gold.fact_sales;

-- Find total customers by countries.
SELECT country, COUNT(customer_id) as total_customers FROM gold.dim_customers GROUP BY country ORDER BY total_customers desc;

-- Find total customers by gender.
SELECT gender, COUNT(customer_id) as total_customers FROM gold.dim_customers GROUP BY gender ORDER BY total_customers desc;

-- Find total products by category.
SELECT category, COUNT(product_id) as total_products FROM gold.dim_products GROUP BY category ORDER BY total_products desc;

-- What is the average costs in each category?
SELECT category, AVG(cost) as avg_cost FROM gold.dim_products GROUP BY category ORDER BY avg_cost desc;

-- What is the total revenue generated by each category?
SELECT 
p.category,
SUM(s.sales_amount) as total_revenue
FROM gold.dim_products as p
INNER JOIN gold.fact_sales as s
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue desc;

-- What is the total revenue generated by each customer?
SELECT c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) as total_revenue
FROM gold.dim_customers as c
INNER JOIN gold.fact_sales as s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue desc;

-- What is the distribution of sold items across countries?
SELECT 
c.country,
SUM(s.quantity) as total_sold_items
FROM gold.dim_customers as c
INNER JOIN gold.fact_sales as s
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_sold_items desc;